apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timeserver.fullname" . }}
  labels:
    {{- include "timeserver.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.config.port | quote }}
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
