apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timeserver.fullname" . }}
  labels:
    {{- include "timeserver.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "timeserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "timeserver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8888
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "timeserver.fullname" . }}
            {{- if .Values.secret.create }}
            - secretRef:
                name: {{ include "timeserver.fullname" . }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
